# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and optionally run tests across different versions of Node.js

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build with Vite
      run: npm run build --if-present

    # Optional: Run tests if you have a test script
    - name: Run tests
      run: npm test
      # Uncomment the following line if you do not have a test script
      # if: false  # Remove or set to true if you have tests to run
